### PR TITLE
Fix movw rX, r0 (provided by yume)

### PR DESCRIPTION
**Pull request by Plaque-fcc**
Signed-off-by: Plaque-fcc <Plaque-fcc@github>

### CODE REVIEW

**Comment by osresearch** [comment]
I'm confused by this one. What happened to `NOP`?

**Comment by Plaque-fcc** [comment]
By default alu_op and alu_store are set to do nothing (NOP).
Due to 0000_000_0000 subsequent 0000_000_???? won't match, since the second case switch also checks opcode[8], it will do nothing on opcode[8]=0 (as desired).

If you have a better solution, it'd be much appreciated.

**Comment by osresearch** [comment]
Ah, that makes sense.  I think a comment on the end of the line to make it clear that NOP is selected would be enough:

```
if (opcode[8] == 1'b1) instr = `is_movw; // else NOP
```

**Comment by Plaque-fcc** [comment]
Agreed. Corrected that.

**Pull request merged**
